"""add follow_up_required to visits

Revision ID: 12cf2f2f3a70
Revises: 2e8e898f6936
Create Date: 2026-07-14 12:50:10.250408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12cf2f2f3a70'
down_revision: Union[str, Sequence[str], None] = '2e8e898f6936'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visits', sa.Column('follow_up_required', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visits', 'follow_up_required')
    # ### end Alembic commands ###
